import { SorteoConfig } from '../types/sorteo';

export const sorteoConfig: SorteoConfig = {
  activo: true,
  empresa: {
    nombre: 'Olney 4x4 Parts',
    razonSocial: 'Olney 4x4 Parts & Equipamiento S.A.',
    cuit: '30-71829340-9',
    direccion: 'Córdoba Capital, Argentina',
    ciudad: 'Córdoba Capital, Argentina',
    instagram: 'https://www.instagram.com/olney4x4parts/',
    instagramHandle: '@olney4x4parts',
    whatsapp: '5493510000000',
    whatsappFormatted: '+54 9 351 000-0000',
    email: 'contacto@olney4x4.com.ar',
  },
  banco: {
    alias: 'OLNEY.4X4.SORTEO',
    titular: 'Olney 4x4 Parts',
    cuit: '30-71829340-9',
    banco: 'Banco Galicia / Mercado Pago',
    tipoCuenta: 'Cuenta Corriente',
  },
  premio: {
    titulo: 'Juego Completo de 4 Cubiertas 4x4 a Elección',
    subtitulo: 'Elegí el set x4 que mejor calce en tu camioneta o SUV (BF Goodrich, Michelin, Kumho, Bridgestone, Pirelli y más)',
    descripcion: '¡Te equipamos la chata completa! El ganador elegirá un juego de 4 cubiertas nuevas 0km entre un catálogo exclusivo de primeras marcas y medidas seleccionadas en stock (A/T, M/T o H/T en rodados 15", 16", 17", 18", 20" y 22").',
    imagen: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80',
    items: [
      'Set de 4 Cubiertas a elección dentro de la selección de medidas y modelos disponibles',
      'Primeras marcas: BF Goodrich, Michelin, Kumho, Bridgestone, Pirelli y más',
      'Variedad de rodados para camionetas y SUVs (15", 16", 17", 18", 20" y 22" según catálogo)',
      'Envío 100% BONIFICADO a cualquier punto del país',
      'O colocación, alineación y balanceo sin cargo en taller Córdoba',
    ],
    fechaSorteo: 'En vivo por Instagram @olney4x4parts',
    mecanismo: 'Transmisión en vivo por Instagram oficial @olney4x4parts con escribano público y registro digital.',
    alcance: 'Válido para todo el territorio de la República Argentina.',
    basesUrl: '/bases',
  },
  packs: [
    {
      id: 'pack-1',
      nombre: 'Pack 1',
      precio: 4500,
      chances: 1,
      cantidadFotos: 10,
      descripcionCorta: 'Las 10 fotos 4x4 de Olney Parts, en alta calidad.',
      caracteristicas: [
        '10 Fotos 4x4 en Alta Calidad',
        '1 Chance para el sorteo',
        'Descarga digital instantánea',
      ],
      imagen: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=600&q=80',
      zipFileName: 'Olney-Pack-1-Fotos-HD.zip',
    },
    {
      id: 'pack-2',
      nombre: 'Pack 2',
      badge: 'MÁS ELEGIDO 🔥',
      popular: true,
      precio: 9900,
      chances: 3,
      cantidadFotos: 10,
      descripcionCorta: 'Las 10 fotos 4x4 de Olney Parts, en alta calidad.',
      caracteristicas: [
        '10 Fotos 4x4 en Alta Calidad',
        '3 Chances para el sorteo',
        'Descarga digital instantánea',
      ],
      imagen: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=600&q=80',
      zipFileName: 'Olney-Pack-2-Fotos-HD.zip',
    },
    {
      id: 'pack-3',
      nombre: 'Pack 3',
      badge: 'MEJOR VALOR ⚡',
      precio: 19900,
      chances: 7,
      cantidadFotos: 10,
      descripcionCorta: 'Las 10 fotos 4x4 de Olney Parts, en alta calidad.',
      caracteristicas: [
        '10 Fotos 4x4 en Alta Calidad',
        '7 Chances para el sorteo',
        'Descarga digital instantánea',
      ],
      imagen: 'https://images.unsplash.com/photo-1551830820-330a713d166c?auto=format&fit=crop&w=600&q=80',
      zipFileName: 'Olney-Pack-3-Fotos-HD.zip',
    },
    {
      id: 'pack-4',
      nombre: 'Pack 4',
      badge: 'MÁXIMAS CHANCES 👑',
      precio: 39900,
      chances: 15,
      cantidadFotos: 10,
      descripcionCorta: 'Las 10 fotos 4x4 de Olney Parts, en alta calidad.',
      caracteristicas: [
        '10 Fotos 4x4 en Alta Calidad',
        '15 Chances para el sorteo',
        'Descarga digital instantánea',
      ],
      imagen: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=600&q=80',
      zipFileName: 'Olney-Pack-4-Fotos-HD.zip',
    },
  ],
  gratis: {
    activa: true,
    chances: 1,
    formularioUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSdhJiCHA5Wlr34Kh2MWzu9DMexnroKgR3b-oUjBCL9OhhTiiQ/viewform',
    whatsappMensaje: 'Hola Olney 4x4! Quiero participar GRATIS del sorteo del juego de cubiertas (Sin obligación de compra). Mis datos son: Nombre completo: ... / DNI: ... / Teléfono: ...',
    instrucciones: 'Conforme a la normativa legal vigente en la República Argentina, podés participar de manera gratuita (1 chance por persona y por DNI) completando el formulario de registro o contactándonos por WhatsApp con tus datos reales.',
  },
  faqs: [
    {
      pregunta: '¿Cómo sé que ya estoy participando del sorteo?',
      respuesta: 'Una vez que realizás la transferencia bancaria con el monto exacto del pack elegido a nuestro alias oficial, tu comprobante y número de operación bancaria quedan registrados automáticamente en nuestro sistema con la cantidad de chances correspondiente.',
    },
    {
      pregunta: '¿Qué marcas y medidas de cubiertas se sortean?',
      respuesta: 'El ganador elegirá su juego completo de 4 cubiertas entre una lista exclusiva de primeras marcas (BF Goodrich, Michelin, Kumho, Bridgestone, Pirelli, Sunset, etc.) en medidas y rodados seleccionados para camionetas y SUVs (15", 16", 17", 18", 20" y 22" según catálogo en stock).',
    },
    {
      pregunta: '¿Qué costo tiene el envío si gano?',
      respuesta: '¡El envío es 100% GRATIS a cualquier localidad de la República Argentina! Si vivís o te acercás a Córdoba Capital, también te bonificamos la instalación, colocación y balanceo en taller.',
    },
    {
      pregunta: '¿Cómo descargo mi pack de fotos digitales?',
      respuesta: 'En la sección de confirmación, adjuntás la captura o comprobante de tu transferencia y se habilitará de inmediato el botón para descargar el archivo ZIP con todas las fotos en alta resolución.',
    },
    {
      pregunta: '¿Cuándo y cómo se realiza el sorteo?',
      respuesta: 'El sorteo se transmitirá en vivo a través de nuestra cuenta oficial de Instagram @olney4x4parts con escribano público y total transparencia. La fecha y hora exacta se anunciarán con anticipación por nuestras redes oficiales.',
    },
    {
      pregunta: '¿Es obligatorio comprar para participar?',
      respuesta: 'No. El sorteo es sin obligación de compra. Podés solicitar tu participación gratuita (1 chance por persona y por DNI) a través del enlace de participación gratuita que figura en el sitio.',
    },
  ],
};
